CREATE TABLE IF NOT EXISTS
	SYSTEM_NOTIFICATIONS (
		ID VARCHAR(255) NOT NULL PRIMARY KEY,
		NTYPE SMALLINT NOT NULL,
		TITLE VARCHAR NOT NULL,
		MESSAGE VARCHAR,
		LEVEL SMALLINT NOT NULL,
		EXPIRATION TIMESTAMP,
		CREATION TIMESTAMP NOT NULL
	);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_NTYPE ON SYSTEM_NOTIFICATIONS(NTYPE);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_LEVEL ON SYSTEM_NOTIFICATIONS(LEVEL);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_EXPIRATION ON SYSTEM_NOTIFICATIONS(EXPIRATION);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_CREATION ON SYSTEM_NOTIFICATIONS(CREATION);

CREATE TABLE IF NOT EXISTS
	SYSTEM_NOTIFICATIONS_ACKS (
		ID VARCHAR(255) NOT NULL,
		USER VARCHAR(255) NOT NULL,
		FOREIGN KEY(ID) REFERENCES SYSTEM_NOTIFICATIONS(ID)
	);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_ACKS_USER ON SYSTEM_NOTIFICATIONS_ACKS(USER);