CREATE TABLE IF NOT EXISTS
	USER_PROFILE_SETTINGS (
		TOKEN VARCHAR(255) NOT NULL,
		PATH VARCHAR(255) NOT NULL,
		DATA VARCHAR
	);

CREATE UNIQUE INDEX IF NOT EXISTS USER_PROFILE_SETTINGS_UNIQUE ON USER_PROFILE_SETTINGS(TOKEN, PATH);
CREATE INDEX IF NOT EXISTS USER_PROFILE_SETTINGS_TOKEN ON USER_PROFILE_SETTINGS(TOKEN);
CREATE INDEX IF NOT EXISTS USER_PROFILE_SETTINGS_PATH ON USER_PROFILE_SETTINGS(PATH);